{% set name = "stomp.py" %}
{% set version = "8.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d2bc55b4596604feb51d56895d93431ff8ee159b31b28d9038a2310777bbd3fa

build:
  number: 1
  entry_points:
    - stomp = stomp.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6,<4.0
  run:
    - docopt >=0.6.2,<0.7.0
    - python >=3.6,<4.0

test:
  imports:
    - stomp
    - stomp.adapter
  commands:
    - pip check
    - stomp --help
  requires:
    - pip

about:
  home: https://github.com/jasonrbriggs/stomp.py
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python STOMP client, supporting versions 1.0, 1.1 and 1.2 of the protocol
  description: |
    "stomp.py" is a Python client library for accessing messaging servers
    (such as ActiveMQ, Artemis or RabbitMQ) using the STOMP protocol
    (STOMP v1.0, STOMP v1.1 and STOMP v1.2).
    It can also be run as a standalone, command-line client for testing.
  doc_url: https://jasonrbriggs.github.io/stomp.py/
  dev_url: https://github.com/jasonrbriggs/stomp.py

extra:
  recipe-maintainers:
    - anthchirp
    - deepsworld
